vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        photo_images:
            uri_prefix: /images/photo
            upload_destination: "%kernel.project_dir%/public/images/photo"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        categorie_images:
            uri_prefix: /images/categorie
            upload_destination: "%kernel.project_dir%/public/images/categorie"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer